/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.JOptionPane;
import model.BaiDang;
import model.DuLieu;
public class QuanLyBaiDangForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuanLyBaiDangForm.class.getName());

    /**
     * Creates new form QuanLyBaiDangForm
     */
    
       public QuanLyBaiDangForm() {
    initComponents();

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblBaiDang.getModel();

    model.setRowCount(0);

    for (BaiDang bd : DuLieu.dsBaiDang) {
    model.addRow(new Object[]{
        model.getRowCount() + 1,
        bd.getTieuDe(),
        bd.getDanhMuc(),
        bd.getMoTa(),
        bd.getLienHe(),
        bd.getTrangThai()
    });
}
}
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBaiDang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhatTrangThai = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        btnKhoaTaiKhoan = new javax.swing.JButton();
        btnMoTaiKhoan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblBaiDang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tiêu đề", "Danh mục", "Mô tả", "Liên hệ", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(tblBaiDang);

        jLabel1.setText("QUẢN LÝ BÀI ĐĂNG");

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhatTrangThai.setText("Cập Nhật Trạng Thái");
        btnCapNhatTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatTrangThaiActionPerformed(evt);
            }
        });

        btnQuayLai.setText("Quay Lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        btnKhoaTaiKhoan.setText("Khoá tài khoản");
        btnKhoaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaTaiKhoanActionPerformed(evt);
            }
        });

        btnMoTaiKhoan.setText("Mở tài khoản");
        btnMoTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoTaiKhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKhoaTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMoTaiKhoan)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(294, 294, 294))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuayLai)
                    .addComponent(btnCapNhatTrangThai)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSua)
                        .addGap(72, 72, 72)
                        .addComponent(btnXoa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnKhoaTaiKhoan)
                        .addComponent(btnMoTaiKhoan)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addGap(18, 18, 18)
                .addComponent(btnCapNhatTrangThai)
                .addGap(18, 18, 18)
                .addComponent(btnQuayLai)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatTrangThaiActionPerformed
 int row = tblBaiDang.getSelectedRow();

    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Vui lòng chọn bài đăng!"
        );
        return;
    }

String trangThai =
        tblBaiDang.getValueAt(row, 5).toString();

    if(trangThai.equals("Đã trả")){
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Bài đăng này đã được trả!"
        );
        return;
    }

BaiDang bd = DuLieu.dsBaiDang.get(row);
bd.setTrangThai("Đã trả");

tblBaiDang.setValueAt("Đã trả", row, 5);

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Cập nhật thành công!"
    );
    }//GEN-LAST:event_btnCapNhatTrangThaiActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
  MenuForm form = new MenuForm();
    form.setVisible(true);

    this.dispose();        
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
 int row = tblBaiDang.getSelectedRow();

    if(row == -1){
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Vui lòng chọn bài đăng cần xóa!"
        );
        return;
    }

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblBaiDang.getModel();

    DuLieu.dsBaiDang.remove(row);
model.removeRow(row);

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Xóa thành công!"
    );        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
  int row = tblBaiDang.getSelectedRow();

if(row == -1){
    JOptionPane.showMessageDialog(
            this,
            "Vui lòng chọn bài đăng cần sửa!"
    );
    return;
}

BaiDang bd = DuLieu.dsBaiDang.get(row);

String tieuDeMoi = JOptionPane.showInputDialog(
        this,
        "Tiêu đề mới:",
        bd.getTieuDe()
);

String moTaMoi = JOptionPane.showInputDialog(
        this,
        "Mô tả mới:",
        bd.getMoTa()
);

String lienHeMoi = JOptionPane.showInputDialog(
        this,
        "Liên hệ mới:",
        bd.getLienHe()
);

if(tieuDeMoi != null){
    bd.setTieuDe(tieuDeMoi);
}
if(moTaMoi != null){
    bd.setMoTa(moTaMoi);
}
if(lienHeMoi != null){
    bd.setLienHe(lienHeMoi);
}

tblBaiDang.setValueAt(bd.getTieuDe(), row, 1);
tblBaiDang.setValueAt(bd.getMoTa(), row, 3);
tblBaiDang.setValueAt(bd.getLienHe(), row, 4);

JOptionPane.showMessageDialog(
        this,
        "Sửa thành công!"
);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnKhoaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaTaiKhoanActionPerformed
        int selectedRow = tblBaiDang.getSelectedRow(); 
    
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một bài đăng để khóa tài khoản người đăng!");
        return;
    }
    
    // 2. Sử dụng tài khoản mẫu "user1" trong hệ thống dữ liệu để demo cho thầy cô xem
    String usernameCanKhoa = "user1"; 
    
    // 3. Tìm tài khoản trong DuLieu.dsUser và cập nhật trạng thái bị khóa (true)
    boolean timThay = false;
    for (model.User u : model.DuLieu.dsUser) {
        if (u.getUsername().equals(usernameCanKhoa)) {
            u.setLocked(true); // Đổi trạng thái tài khoản thành Bị Khóa
            timThay = true;
            break;
        }
    }
    
    // 4. Bật hộp thoại thông báo thành công cho Admin biết
    if (timThay) {
        javax.swing.JOptionPane.showMessageDialog(this, "Đã khóa thành công tài khoản người dùng: " + usernameCanKhoa);
    }// TODO add your handling code here:
    }//GEN-LAST:event_btnKhoaTaiKhoanActionPerformed

    private void btnMoTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoTaiKhoanActionPerformed
        // 1. Kiểm tra xem người dùng đã chọn dòng nào trên bảng chưa
    int selectedRow = tblBaiDang.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một bài đăng để mở khóa tài khoản!");
        return;
    }
    
    // 2. Tài khoản demo thực tế
    String usernameCanMo = "user1"; 
    
    // 3. Tìm tài khoản trong danh sách và chuyển trạng thái hoạt động trở lại (false)
    boolean timThay = false;
    for (model.User u : model.DuLieu.dsUser) {
        if (u.getUsername().equals(usernameCanMo)) {
            u.setLocked(false); // Chuyển sang trạng thái mở khóa
            timThay = true;
            break;
        }
    }
    
    // 4. Thông báo mở thành công
    if (timThay) {
        javax.swing.JOptionPane.showMessageDialog(this, "Đã mở khóa thành công tài khoản người dùng: " + usernameCanMo);
    }// TODO add your handling code here:
    }//GEN-LAST:event_btnMoTaiKhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QuanLyBaiDangForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatTrangThai;
    private javax.swing.JButton btnKhoaTaiKhoan;
    private javax.swing.JButton btnMoTaiKhoan;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBaiDang;
    // End of variables declaration//GEN-END:variables
}
